;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        /mark-next-like-this
        backward-delete-word
        backward-sexp
        cua--prefix-repeat-handler
        cua--shift-control-c-prefix
        cua-copy-region
        cua-cut-region
        cua-delete-region
        cua-paste
        dabbrev-expand
        delete-word
        forward-sexp
        highlight-symbol-prev
        hydra-mc/mc/mark-previous-like-this
        kill-region
        org-yank
        seq-end
        seq-home
        skk-insert
        skk-mode
        sp--cua-replace-region
        sp--self-insert-command
        typescript-insert-and-indent
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        helm-confirm-and-exit-minibuffer
        highlight-symbol-next
        hydra-mc/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-next-like-this
        my/helm
        ))
