;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua--prefix-repeat-handler
        cua--shift-control-c-prefix
        cua-cut-region
        cua-delete-region
        cua-paste
        seq-end
        seq-home
        sp--cua-replace-region
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
