;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        cua--prefix-repeat-handler
        cua--shift-control-c-prefix
        cua-copy-region
        cua-cut-region
        cua-delete-region
        cua-paste
        dabbrev-expand
        delete-word
        forward-sexp
        kill-region
        org-yank
        seq-end
        seq-home
        skk-mode
        sp--cua-replace-region
        sp--self-insert-command
        typescript-insert-and-indent
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
